#ifndef PARAMS_H
#define PARAMS_H

#define CRYPTO_ALGNAME "ecdhe"

#define ECDHE_CURVE_P256 1

#define ECDHE_CURVE ECDHE_CURVE_P256

#define ECDHE_PUBLICKEYBYTES 65
#define ECDHE_PRIVATEKEYBYTES 32

#endif
