#ifndef PARAMS_H
#define PARAMS_H

#define CRYPTO_ALGNAME "ecdhe"

#define ECDHE_CURVE_P256 1

#define ECDHE_CURVE ECDHE_CURVE_P256

#define CRYPTO_PUBLICKEYBYTES 65
#define CRYPTO_SECRETKEYBYTES 32
#define CRYPTO_BYTES 32
#define CRYPTO_SECRETBYTES 32

#endif
