#ifndef PARAMS_H
#define PARAMS_H

#define NTRU_HRSS_701 1
#define NTRU_HPS_4096821 2

#ifndef NTRU_PARAMETER_SET
#define NTRU_PARAMETER_SET NTRU_HRSS_701
#endif

#if NTRU_PARAMETER_SET == NTRU_HRSS_701
#define NTRU_HRSS
#define NTRU_N 701
#define NTRU_LOGQ 13

#define CRYPTO_ALGNAME "ntruhrss701"
#define CRYPTO_SECRETKEYBYTES 1450
#define CRYPTO_PUBLICKEYBYTES 1138
#define CRYPTO_CIPHERTEXTBYTES 1138
#elif NTRU_PARAMETER_SET == NTRU_HPS_4096821
#define NTRU_HPS
#define NTRU_N 821
#define NTRU_LOGQ 12

#define CRYPTO_ALGNAME "ntruhps4096821"
#define CRYPTO_SECRETKEYBYTES 1590
#define CRYPTO_PUBLICKEYBYTES 1230
#define CRYPTO_CIPHERTEXTBYTES 1230
#elif NTRU_PARAMETER_SET == NTRU_HPS_2048677
#define NTRU_HPS
#define NTRU_N 677
#define NTRU_LOGQ 11

#define CRYPTO_ALGNAME "ntruhps2048677"
#define CRYPTO_PUBLICKEYBYTES 930
#define CRYPTO_SECRETKEYBYTES 1234
#define CRYPTO_CIPHERTEXTBYTES 930
#define CRYPTO_BYTES 32
#elif NTRU_PARAMETER_SET == NTRU_HPS_2048509
#define NTRU_HPS
#define NTRU_N 509
#define NTRU_LOGQ 11

#define CRYPTO_ALGNAME "ntruhps2048509"
#define CRYPTO_SECRETKEYBYTES 935
#define CRYPTO_PUBLICKEYBYTES 699
#define CRYPTO_CIPHERTEXTBYTES 699
#define CRYPTO_BYTES 32
#endif

#define CRYPTO_BYTES 32

/* Do not modify below this line */

#define PAD32(X) ((((X) + 31)/32)*32)

#define NTRU_Q (1 << NTRU_LOGQ)

#ifdef NTRU_HPS
#define NTRU_WEIGHT (NTRU_Q / 8 - 2)
#endif

#define NTRU_SEEDBYTES       32
#define NTRU_PRFKEYBYTES     32
#define NTRU_SHAREDKEYBYTES  32

#define NTRU_SAMPLE_IID_BYTES  (NTRU_N-1)

#ifdef NTRU_HRSS
#define NTRU_SAMPLE_FG_BYTES   (2*NTRU_SAMPLE_IID_BYTES)
#define NTRU_SAMPLE_RM_BYTES   (2*NTRU_SAMPLE_IID_BYTES)
#elif defined NTRU_HPS
#define NTRU_SAMPLE_FT_BYTES ((30 * (NTRU_N - 1) + 7) / 8)
#define NTRU_SAMPLE_FG_BYTES (NTRU_SAMPLE_IID_BYTES + NTRU_SAMPLE_FT_BYTES)
#define NTRU_SAMPLE_RM_BYTES (NTRU_SAMPLE_IID_BYTES + NTRU_SAMPLE_FT_BYTES)
#endif

#define NTRU_PACK_DEG (NTRU_N-1)
#define NTRU_PACK_TRINARY_BYTES    ((NTRU_PACK_DEG+4)/5)

#define NTRU_OWCPA_MSGBYTES       (2*NTRU_PACK_TRINARY_BYTES)
#define NTRU_OWCPA_PUBLICKEYBYTES ((NTRU_LOGQ*NTRU_PACK_DEG+7)/8)
#define NTRU_OWCPA_SECRETKEYBYTES (2*NTRU_PACK_TRINARY_BYTES + NTRU_OWCPA_PUBLICKEYBYTES)
#define NTRU_OWCPA_BYTES          ((NTRU_LOGQ*NTRU_PACK_DEG+7)/8)

#define NTRU_PUBLICKEYBYTES  (NTRU_OWCPA_PUBLICKEYBYTES)
#define NTRU_SECRETKEYBYTES  (NTRU_OWCPA_SECRETKEYBYTES + NTRU_PRFKEYBYTES)
#define NTRU_CIPHERTEXTBYTES (NTRU_OWCPA_BYTES)

#endif
